basePath: /
definitions:
  models.Chat:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      type:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  transport.InputAuth:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  transport.transort_error:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: HealthMate
  version: "1.0"
paths:
  /api/v1/chats/:
    get:
      consumes:
      - application/json
      description: Get all chats
      operationId: get-all-chats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get all chats
      tags:
      - chats
    post:
      consumes:
      - application/json
      description: create chat
      operationId: create-chat
      parameters:
      - description: chat info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Chat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Create chat
      tags:
      - chats
  /api/v1/chats/{chat_id}/:
    get:
      consumes:
      - application/json
      description: Get all messages
      operationId: get-all-messages
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get all messages
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Create message
      operationId: create-message
      parameters:
      - description: message info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Create message
      tags:
      - message
  /api/v1/chats/{chat_id}/{message_id}:
    delete:
      consumes:
      - application/json
      description: Delete message by Id
      operationId: delete-message-by-id
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: integer
      - description: Message ID
        in: path
        name: message_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Delete message by Id
      tags:
      - messages
    get:
      consumes:
      - application/json
      description: Get message by Id
      operationId: get-message-by-id
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: integer
      - description: Message ID
        in: path
        name: message_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get message by Id
      tags:
      - messages
    put:
      consumes:
      - application/json
      description: Update message by Id
      operationId: update-message
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: integer
      - description: Message ID
        in: path
        name: message_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Update message
      tags:
      - messages
  /api/v1/chats/{id}:
    delete:
      consumes:
      - application/json
      description: Delete chat by Id
      operationId: delete-chat
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Delete Chat
      tags:
      - chats
    get:
      consumes:
      - application/json
      description: Get chat by Id
      operationId: get-chat-by-id
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Get Chat by Id
      tags:
      - chats
    put:
      consumes:
      - application/json
      description: Update chat by Id
      operationId: update-chat
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Update Chat
      tags:
      - chats
  /api/v1/files/upload:
    post:
      consumes:
      - application/json
      description: Upload file
      operationId: upload-file
      parameters:
      - description: Body with file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      security:
      - ApiKeyAuth: []
      summary: Upload file
      tags:
      - files
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login to account
      operationId: login-to-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/transport.InputAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.transort_error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.transort_error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.transort_error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/transport.transort_error'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
